- name: update cache if old
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: fix Scaleway.com nasties
  file:
    path: "{{ item }}"
    mode: "g-w"
  with_items:
    - /etc
    - /usr

- name: install basic packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
