- include: base.yml

- name: add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 41A6970FF48EB5DA9B81BB6C66EB83CBEBD4FBB3

- name: add siderus repository
  apt_repository:
    filename: siderus.list
    repo: deb https://get.siderus.io/ apt/
    state: present
  notify:
    - update apt cache
    - install packages

##Firewall
- name: allow services
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - ssh
    - http
    - 4001
  notify: enable ufw


## ipfs
- name: add ipfs user
  user:
    name: ipfs
    shell: /usr/sbin/nologin
    password: '!'
    home: /opt/ipfs
  notify: initialize ipfs


- name: copy service
  copy:
    src: "files/ipfs.service"
    dest: "/etc/systemd/system"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: enable ipfs service

#Pinner
- name: deploy pinning webui
  copy:
    src: files/pinner
    dest: /srv/http/
    owner: ipfs
    group: ipfs
    mode: 0644

#Proxy
- name: configure nginx
  copy:
    src: "files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: enable nginx
