- name: enable ufw
  ufw:
    state: enabled

- name: enable ipfs service
  systemd:
    name: ipfs
    enabled: yes
    state: started

- name: enable nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
